// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1

type GeneratedRevisionSpecConverter struct{}

func (c *GeneratedRevisionSpecConverter) v1TypeReferenceToV1TypeReference(source TypeReference) TypeReference {
	var v1TypeReference TypeReference
	v1TypeReference.APIVersion = source.APIVersion
	v1TypeReference.Kind = source.Kind
	return v1TypeReference
}

func (c *GeneratedRevisionSpecConverter) ToRevisionSpec(source CompositionSpec) CompositionRevisionSpec {
	var v1CompositionRevisionSpec CompositionRevisionSpec
	v1CompositionRevisionSpec.CompositeTypeRef = c.v1TypeReferenceToV1TypeReference(source.CompositeTypeRef)
	var pV1CompositionMode *CompositionMode
	if source.Mode != nil {
		v1CompositionMode := CompositionMode(*source.Mode)
		pV1CompositionMode = &v1CompositionMode
	}
	v1CompositionRevisionSpec.Mode = pV1CompositionMode
	return v1CompositionRevisionSpec
}
