# permissions for end users to edit compositionrevisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: builderxplane
    app.kubernetes.io/managed-by: kustomize
  name: compositionrevision-editor-role
rules:
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositionrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositionrevisions/status
  verbs:
  - get
