# permissions for end users to view compositions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: builderxplane
    app.kubernetes.io/managed-by: kustomize
  name: composition-viewer-role
rules:
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositions/status
  verbs:
  - get
