---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositionrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositionrevisions/finalizers
  verbs:
  - update
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositionrevisions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositions/finalizers
  verbs:
  - update
- apiGroups:
  - apiextensions.xplane.io
  resources:
  - compositions/status
  verbs:
  - get
  - patch
  - update
